version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 05082024
    ports:
      - "3306:3306" 
    expose:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: mysql:8.0
    container_name: app_container
    environment:
      DATABASE_URL: mysql://myuser:05082024@db:3306/mydatabase
    depends_on:
      - db

volumes:
  mysql_data:
